[build]
target = "x86_64-unknown-none"
rustflags = [
	"-C", "force-frame-pointers",
	"-C", "linker-flavor=ld",
	"--cfg", "aes_force_soft",
	"--cfg", "polyval_force_soft",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
       "-C", "code-model=kernel",
]

[alias]
vfmt = "run-script vfmt" # Format verus codes
verify = "v build --features verus"
vinstall = "install --git https://github.com/microsoft/verismo/ -rev 8e2bc86f59c4a085a8e790b31a40170e6a8b8c21  cargo-v"
