name: Verification	

on:	
  pull_request:	
    branches: [ "main-verify" ]

env:	
  CARGO_TERM_COLOR: always	

jobs:	
  check:	
    name: Verification Check	
    runs-on: ubuntu-latest	
    steps:	
      - name: Checkout	
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: fetch verus via metadata	
        run: |	
            source ./scripts/vpath.sh	
            echo "VERUS_PATH=$(echo $VERUS_PATH)" >> $GITHUB_ENV	
      - uses: Swatinem/rust-cache@v2
        with:	
          cache-directories: ${{ env.VERUS_PATH }}/source/target-verus	
          workspaces: |	
            ${{ github.workspace }} -> target	
            ${{ env.VERUS_PATH }}/source -> target	
            ${{ env.VERUS_PATH }}/tools/vargo -> target
      - name: Install specified rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: '1.82.0'
            target: x86_64-unknown-none
            profile: minimal
            override: true
            components: rustfmt, rust-src, clippy

      - name: Install verus toolchains	
        run: ./scripts/vinstall.sh	

      - name: Format rust code
        run: verusfmt --check `find ./ -name *.verus.rs`

      - name: Verify svsm with verus	
        run: cargo verify	
        working-directory: kernel	

      - name: Verify extra proof libs with verus	
        run: cargo verify	
        working-directory: verify_proof	

      - name: Build without verifying	
        run: cargo build	
        working-directory: kernel