name: Verification

on:
  push:
    branches: [ "verify" ]
  pull_request:
    branches: [ "verify" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Verification Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: fetch verus via metadata
        run: |
            source ./scripts/vpath.sh
            echo "VERUS_PATH=$(echo $VERUS_PATH)" >> $GITHUB_ENV

      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ${{ env.VERUS_PATH }}/source/target-verus
          workspaces: |
            ${{ github.workspace }} -> target
            ${{ env.VERUS_PATH }}/source -> target
            ${{ env.VERUS_PATH }}/tools/vargo -> target

      - name: Install specified rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-12-22
          target: x86_64-unknown-none
          profile: minimal

      - name: Install verus toolchains
        run: ./scripts/vinstall.sh

      - name: Build with verus
        run: cargo verify
        working-directory: kernel

      - name: Build without verifying
        run: cargo build
        working-directory: kernel

      - name: Format rust code
        run: verusfmt --check `find ./ -name *.verus.rs`

