name: Rust

on:
  push:
    branches: [ "verify" ]
  pull_request:
    branches: [ "verify" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Verification Check
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set VERUS_PATH
        run: echo "VERUS_PATH=$(realpath ../verus)" >> $GITHUB_ENV

      - name: Install verus-rustc
        run: cargo install cargo-run-script && cargo vinstall

      - name: Build with verus
        run: source ../scripts/vactivate.sh && rustup show && cargo v
        working-directory: kernel

      - name: Build without verifying
        run: source ../scripts/vactivate.sh deactivate && rustup show && cargo b
        working-directory: kernel

      - name: Format rust code
        run: verusfmt --check `find ./ -name *.verus.rs`

