name: Rust

on:
  push:
    branches: [ "verify" ]
  pull_request:
    branches: [ "verify" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install verus-rustc
        run: cargo vdep && cargo vinstall

      - name: Build with verus
        run: cargo v
        working-directory: kernel

      - name: Build without verifying
        run: cargo b
        working-directory: kernel

      - name: Format rust code
        run: verusfmt --check `find ./ -name *.verus.rs`

